#!/usr/bin/env python3

import argparse
import sys

from pyhsi.GUI import PyHSI


def main(args):
    parser = argparse.ArgumentParser(description="Launch PyHSI GUI")
    parser.add_argument('-d', '--debug', action='store_true', help="print debug information to console")
    opts = parser.parse_args(args)
    app = PyHSI(debug=opts.debug)
    app.run()


if __name__ == '__main__':
    main(sys.argv[1:])
